name: Build & Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build frontend image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./Front/app

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest